#!/usr/bin/python3
def raise_exception():
    a = "test"
    result = a/2
